// <auto-generated />
using System;
using IodEnterpriseApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IodEnterpriseApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260628040134_AddVisitorCardAndDesignation")]
    partial class AddVisitorCardAndDesignation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("IodEnterpriseApi.Models.AttendanceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckInMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("IodEnterpriseApi.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            Action = "Visitor Check-in",
                            Details = "Checked in Rajesh Kumar from ABC Solutions Ltd. Card scanned successfully.",
                            Severity = "info",
                            Timestamp = new DateTime(2026, 6, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            User = "Satish Singh (Guard)"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Action = "GPS Office Duty Start",
                            Details = "Employee Shubham Kumar initiated out-of-office GPS Duty Tracking (Destination: Nehru Place).",
                            Severity = "info",
                            Timestamp = new DateTime(2026, 6, 26, 11, 50, 0, 0, DateTimeKind.Utc),
                            User = "System"
                        });
                });

            modelBuilder.Entity("IodEnterpriseApi.Models.LocationCoordinate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DutyLogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DutyLogId");

                    b.ToTable("LocationCoordinates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            DutyLogId = new Guid("33333333-3333-3333-3333-333333333331"),
                            Latitude = "rP+BJT4CoGr4zB1FP7YZsX84n6UXjBvRX/RQ0oRGews=",
                            Longitude = "YvELSMD+zZUMhBJp9lP2EvSIOtY5IId7JsM1h3QZJDg=",
                            Timestamp = new DateTime(2026, 6, 26, 11, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            DutyLogId = new Guid("33333333-3333-3333-3333-333333333331"),
                            Latitude = "XVr6KWgoaCWtUx/v41yK0UlGbCGIp0slEeji0Ta7y+E=",
                            Longitude = "U1ciIk1IH0s7xFPTFrN8I2TdhGpIV4m907konxpujoE=",
                            Timestamp = new DateTime(2026, 6, 26, 11, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            DutyLogId = new Guid("33333333-3333-3333-3333-333333333331"),
                            Latitude = "0y9tMOklskchCZv5i67UMyXEODma5lHs94uGOoRGAm8=",
                            Longitude = "HZAwB09YcxTx49tBX4NSaDDl6tYr9GoWZtvFeE+TjhA=",
                            Timestamp = new DateTime(2026, 6, 26, 11, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            DutyLogId = new Guid("33333333-3333-3333-3333-333333333331"),
                            Latitude = "HkDaF0Xp6Li7y9T9QrzGqtLtdi7v4yU1alKsFwG7A0Q=",
                            Longitude = "pc6OHC0Q56JBzz4uhmgHf0tbkCyXfwVI772zxEKuvLc=",
                            Timestamp = new DateTime(2026, 6, 26, 11, 55, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444445"),
                            DutyLogId = new Guid("33333333-3333-3333-3333-333333333332"),
                            Latitude = "fwftNmz2rTT1U5Yv30UQFmxYPST8BsRrCVljLHs7U+k=",
                            Longitude = "fz4riaYEZUDosxXfRp6rje48qky2Ta/pVy4Z7GxbLnQ=",
                            Timestamp = new DateTime(2026, 6, 26, 11, 35, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444446"),
                            DutyLogId = new Guid("33333333-3333-3333-3333-333333333332"),
                            Latitude = "8P6phwpwx5WRHGuAbpy4tUibb2EIpYh3hOd/M0fl4I4=",
                            Longitude = "tYffEipTBNERh/QoLOKtWu7lUQR66oIXQy+ivmhWtvM=",
                            Timestamp = new DateTime(2026, 6, 26, 11, 50, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("IodEnterpriseApi.Models.OfficeDutyLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StopTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OfficeDutyLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            Destination = "Nehru Place Client Center",
                            EmployeeId = new Guid("00000000-0000-0000-0000-000000000002"),
                            EmployeeName = "Shubham Kumar",
                            Reason = "Hardware installation & website training for Directors",
                            StartTime = new DateTime(2026, 6, 26, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            Destination = "Connaught Place Head Office",
                            EmployeeId = new Guid("00000000-0000-0000-0000-000000000003"),
                            EmployeeName = "Anita Sharma",
                            Reason = "Quarterly HR compliance audit",
                            StartTime = new DateTime(2026, 6, 26, 11, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("IodEnterpriseApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivationCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveTokenId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentOtp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("FaceRegistered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeviceRegistered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QrLoginToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredDeviceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Department = "Web & IT",
                            Designation = "General Manager",
                            Email = "admin@iod.com",
                            FaceRegistered = true,
                            FirstName = "Ravi Shankar",
                            IsActive = true,
                            IsDeviceRegistered = false,
                            LastName = "Swami",
                            PasswordHash = "hashed_admin123",
                            Phone = "+91-9988776655",
                            PhotoUrl = "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Department = "Web & IT",
                            Designation = "Software Engineering Intern",
                            Email = "shubham@iod.com",
                            FaceRegistered = true,
                            FirstName = "Shubham",
                            IsActive = true,
                            IsDeviceRegistered = false,
                            LastName = "Kumar",
                            PasswordHash = "hashed_staff123",
                            Phone = "+91-9876543210",
                            PhotoUrl = "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150",
                            Role = "Staff"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Department = "Human Resources",
                            Designation = "HR Lead",
                            Email = "anita.hr@iod.com",
                            FaceRegistered = false,
                            FirstName = "Anita",
                            IsActive = true,
                            IsDeviceRegistered = false,
                            LastName = "Sharma",
                            PasswordHash = "hashed_staff123",
                            Phone = "+91-8888777766",
                            PhotoUrl = "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
                            Role = "Staff"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Department = "Security Operations",
                            Designation = "Lobby Security Supervisor",
                            Email = "guard@iod.com",
                            FaceRegistered = true,
                            FirstName = "Satish",
                            IsActive = true,
                            IsDeviceRegistered = false,
                            LastName = "Singh",
                            PasswordHash = "hashed_guard123",
                            Phone = "+91-7777666655",
                            PhotoUrl = "https://images.unsplash.com/photo-1621574539437-4b7cb63120b8?w=150",
                            Role = "SecurityGuard"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Department = "Corporate Affairs",
                            Designation = "Executive Director",
                            Email = "exec@iod.com",
                            FaceRegistered = true,
                            FirstName = "Arun",
                            IsActive = true,
                            IsDeviceRegistered = false,
                            LastName = "Bajaj",
                            PasswordHash = "hashed_staff123",
                            Phone = "+91-9999888877",
                            PhotoUrl = "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
                            Role = "Staff"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Department = "Finance & Accounting",
                            Designation = "Senior Analyst",
                            Email = "analyst@iod.com",
                            FaceRegistered = true,
                            FirstName = "Priya",
                            IsActive = true,
                            IsDeviceRegistered = false,
                            LastName = "Menon",
                            PasswordHash = "hashed_staff123",
                            Phone = "+91-8888999900",
                            PhotoUrl = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
                            Role = "Staff"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Department = "Web & IT",
                            Designation = "IT Administrator",
                            Email = "itadmin@iod.com",
                            FaceRegistered = false,
                            FirstName = "Karthik",
                            IsActive = true,
                            IsDeviceRegistered = false,
                            LastName = "Raman",
                            PasswordHash = "hashed_staff123",
                            Phone = "+91-7777888899",
                            PhotoUrl = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
                            Role = "Staff"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Department = "Corporate Affairs",
                            Designation = "Board Secretary",
                            Email = "secretary@iod.com",
                            FaceRegistered = true,
                            FirstName = "Sneha",
                            IsActive = true,
                            IsDeviceRegistered = false,
                            LastName = "Rao",
                            PasswordHash = "hashed_staff123",
                            Phone = "+91-6666777788",
                            PhotoUrl = "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150",
                            Role = "Staff"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Department = "Security Operations",
                            Designation = "Security Specialist",
                            Email = "security@iod.com",
                            FaceRegistered = false,
                            FirstName = "Vikram",
                            IsActive = true,
                            IsDeviceRegistered = false,
                            LastName = "Singh",
                            PasswordHash = "hashed_guard123",
                            Phone = "+91-5555666677",
                            PhotoUrl = "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150",
                            Role = "SecurityGuard"
                        });
                });

            modelBuilder.Entity("IodEnterpriseApi.Models.VisitorPass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CardScanned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostDepartment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HostEmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitorCardId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VisitorPasses");
                });

            modelBuilder.Entity("IodEnterpriseApi.Models.WatchlistTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FlaggedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WatchlistTargets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "suresh@blacklisted.com",
                            FirstName = "Suresh",
                            FlaggedAt = new DateTime(2026, 5, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Mehta",
                            Phone = "+91-9000111222",
                            Reason = "Disruptive behavior during General Meeting"
                        });
                });

            modelBuilder.Entity("IodEnterpriseApi.Models.AttendanceLog", b =>
                {
                    b.HasOne("IodEnterpriseApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IodEnterpriseApi.Models.LocationCoordinate", b =>
                {
                    b.HasOne("IodEnterpriseApi.Models.OfficeDutyLog", "DutyLog")
                        .WithMany("Coordinates")
                        .HasForeignKey("DutyLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DutyLog");
                });

            modelBuilder.Entity("IodEnterpriseApi.Models.OfficeDutyLog", b =>
                {
                    b.Navigation("Coordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
